language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
install:                                                                                                                                                                                                                            
  - pip install numpy                                                                                                                                                                                                               
  - pip install matplotlib
script:
  - "python simulatedAnnealingFinal.py"
